project:
  type: website

website:
  title: "Triumvirat Corpus"
  navbar:
    left:
      - href: index.html
        text: Accueil
      - href: books/index.html
        text: Books
      - href: manuscripts/index.html
        text: Manuscripts

format:
  html:
    theme: cosmo
    toc: true
