project:
  type: website

website:
  title: "TriumPortal"
  navbar:
    left:
      - href: index.html
        text: Accueil
      - href: books/index.html
        text: Corpus
      - href: art.html
        text: A.R.T.
      - href: about.html
        text: Ã€ propos

format:
  html:
    theme: cosmo         # sobre et minimaliste
    toc: true
